Server/ControlePassageiros.WebApplication/Controllers/HomeController.cs
using ControlePassageiros.WebApplication.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControlePassageiros.WebApplication.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UsuarioRepository _usuarioRepository;
        private readonly AjaxResult<LoginModel> _ajaxResult;
        private readonly PassageiroRepository _passageiroRepository;


        public HomeController(ILogger<HomeController> logger, UsuarioRepository usuarioRepository, PassageiroRepository passageiroRepository, AjaxResult<LoginModel> ajaxResult)
        {
            _logger = logger;
            _usuarioRepository = usuarioRepository;
            _ajaxResult = ajaxResult;
            _passageiroRepository = passageiroRepository;
        }


        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Controle de Usuários";

            List<PassageiroResponse> response = await ListarPassageirosAsync();

            return View(response);
        }


        public async Task<IActionResult> PesquisarAsync()
        {
            List<PassageiroResponse> response = await ListarPassageirosAsync();
            return View("Listagem", response);
        }


        public IActionResult Login()
        {
            LoginModel model = new LoginModel();

            //model.Login = "marcio.barcellos";
            //model.Senha = "capiau";

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AutenticarAsync(LoginModel model)
        {
            _ajaxResult.Success = false;
            _ajaxResult.Message = "Dados inválidos";

            if (ModelState.IsValid)
            {
                Usuario usuario = await _usuarioRepository.ObterUsuarioLoginAsync(model.Login.ToLower(), model.Senha);

                if (usuario != null)
                {
                    //POPULA O USUARIO LOGADO (ESTATICO) COM OS DADOS DA BASE
                    UsuarioLogado.Criar(usuario);


                    _ajaxResult.Success = true;
                    _ajaxResult.Message = string.Empty;
                    _ajaxResult.Url = "Home/Index";

                    return Ok(_ajaxResult);
                }
            }

            return Ok(_ajaxResult);
        }


        public IActionResult Cadastrar()
        {
            PassageiroRequest model = new PassageiroRequest();
            return View("Formulario", model);
        }


        public async Task<IActionResult> EditarAsync(string rfid)
        {
            Passageiro passageiro = await _passageiroRepository.ObterPorRfidAsync(rfid);

            PassageiroRequest model = new PassageiroRequest
            {
                PassageiroId = passageiro.PassageiroId,
                RfId = passageiro.RfId,
                Condominio = passageiro.Condominio,
                Foto = passageiro.Foto,
                Nome = passageiro.Nome,
                Situacao = passageiro.Situacao,
                Alterado = passageiro.Alterado,
                Email = passageiro.Email?.ToLower(),
                Telefone = passageiro.Telefone,
                DataCadastro = passageiro.DataCadastro.ToShortDateString(),
                Cpf = passageiro.Cpf
            };

            return View("Formulario", model);
        }


        [HttpPost]
        public async Task<JsonResult> IncluirAsync(PassageiroRequest model)
        {
            Passageiro passageiro = new Passageiro
            {
                Alterado = true,
                Nome = model.Nome,
                Condominio = model.Condominio,
                RfId = model.RfId,
                Situacao = model.Situacao,
                Email = model.Email?.ToLower(),
                Telefone = model.Telefone,
                DataCadastro = Convert.ToDateTime(model.DataCadastro),
                Cpf = model.Cpf
            };

            await _passageiroRepository.IncluirAsync(passageiro);

            _ajaxResult.Success = true;
            _ajaxResult.Message = "Usuário cadastrado com sucesso";

            return Json(_ajaxResult);
        }


        [HttpPost]
        public async Task<JsonResult> AlterarAsync(PassageiroRequest model)
        {
            Passageiro passageiro = await _passageiroRepository.ObterPorIdAsync(model.PassageiroId);
            passageiro.Alterado = true;
            passageiro.Condominio = model.Condominio;
            passageiro.Nome = model.Nome;
            passageiro.RfId = model.RfId;
            passageiro.Situacao = model.Situacao;
            passageiro.Email = model.Email?.ToLower();
            passageiro.Telefone = model.Telefone;
            passageiro.DataCadastro = Convert.ToDateTime(model.DataCadastro);
            passageiro.Cpf = model.Cpf;
            

            await _passageiroRepository.AlterarAsync(passageiro);

            _ajaxResult.Success = true;
            _ajaxResult.Message = "Dados alterados com sucesso";

            return Json(_ajaxResult);
        }


        private async Task<List<PassageiroResponse>> ListarPassageirosAsync()
        {
            List<Passageiro> passageiros = await _passageiroRepository.ListarTodosAsync();
            List<PassageiroResponse> response = passageiros.Select(x => new PassageiroResponse
            {
                Rfid = x.RfId,
                Nome = x.Nome,
                Condominio = x.Condominio,
                Foto = x.Foto,
                Situacao = x.Situacao,
                Cpf = x.Cpf,
                DataCadastro = x.DataCadastro,
                Email = x.Email?.ToLower(),
                Telefone = x.Telefone                
            }).ToList();

            return response;
        }
    }
}

Server/ControlePassageiros.WebApplication/Controllers/PassageirosController.cs
using ControlePassageiros.WebApplication.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace ControlePassageiros.WebApplication.Controllers
{
    [AllowAnonymous]
    public class PassageirosController : Controller
    {
        private readonly PassageiroRepository _passageiroRepository;
        private readonly AjaxResult<Passageiro> _ajaxResult;

        public PassageirosController(PassageiroRepository passageiroRepository, AjaxResult<Passageiro> ajaxResult)
        {
            _passageiroRepository = passageiroRepository;
            _ajaxResult = ajaxResult;
        }


        /// <summary>
        /// RETORNA TODOS OS REGISTROS MARCADOS COMO ATUALIZADOS
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> ObterAtualizacoesAsync()
        {
            List<Passageiro> passageiros = await _passageiroRepository.ListarTodosAlteradosAsync();
            List<PassageiroAppResponse> response = passageiros.Select(x => new PassageiroAppResponse
            {
                Ativo = x.Situacao,
                Cartao = x.RfId,
                Nome = x.Nome,
                Condominio = x.Condominio,
                Foto = x.Foto                
            }).ToList();


            return Json(response);
        }


        /// <summary>
        /// CONFIRMACAO DE QUE A BASE DO MARCIO FOI ATUALIZADA E
        /// ATUALIZA O FLAG_ALTERADO PARA FALSE
        /// </summary>
        /// <returns>true</returns>        
        [HttpPost]
        public async Task<JsonResult> ConfirmarAtualizacaoAsync()
        {
            await _passageiroRepository.RemoverFlagAlteradoAsync();
            return Json(true);
        }


        /// <summary>
        /// ALTERA TODOS OS REGISTROS PARA FLAG_ALTERADO 
        /// </summary>
        /// <returns>true</returns>
        [HttpPost]
        public async Task<JsonResult> ResetarBaseAsync(bool? status)
        {
            
            await _passageiroRepository.AtualizarStatusAlteracaoAsync((bool)status);
            _ajaxResult.Success = true;
            _ajaxResult.Message = "Dados resetados com sucesso";

            return Json(_ajaxResult);
        }


        /// <summary>
        /// Bloqueia o Usuário pelo Código de RfId
        /// </summary>
        /// <param name="rfid"></param>
        /// <returns></returns>
        public async Task<JsonResult> BloquearAsync(string rfid)
        {
            await _passageiroRepository.BloquearPorRfidAsync(rfid);

            _ajaxResult.Success = true;
            _ajaxResult.Message = "Usuário bloqueado com sucesso";

            return Json(_ajaxResult);
        }
    }
}

Server/ControlePassageiros.WebApplication/Views/Home/Formulario.cshtml
@model ControlePassageiros.WebApplication.PassageiroRequest
@{
    Layout = null;
}

<div class="card card-form card-box">
    <form id="frmCadastro" method="post" enctype="multipart/form-data">
        @Html.HiddenFor(x => x.PassageiroId)
        @Html.HiddenFor(x => x.Situacao)

        <div id="divCadastro" class="card-body">

            <div class="form-row">
                <div class="col-md-6">
                    @if (!Model.PassageiroId.HasValue)
                    {
                        <img src="~/images/usuario/user-default.png" style="width: 85px; border-radius: 50%;" />
                    }
                    else
                    {
                        <img src="data:image/jpeg;base64,@Model.Foto" style="width: 85px; border-radius: 50%;" />
                    }
                </div>
                <div class="col-md-6 pt-4">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.Situacao, new { @class = "text-uppercase legenda" })</div>
                        <div class="togglebutton">
                            <label id="lblCheckSituacao" style="font-size: 16px; font-weight: bold;">
                                <input id="chkSituacao" type="checkbox" checked="@Model.Situacao"><span class="toggle"></span>
                                Liberado
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.Nome, new { @class = "text-uppercase legenda" })</div>
                        <div class="list-group-item">@Html.TextBoxFor(x => x.Nome, new { @class = "form-control"})</div>
                    </div>
                    @Html.ValidationMessageFor(x => x.Nome)
                </div>
                <div class="col-md-6">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.Condominio, new { @class = "text-uppercase legenda" })</div>
                        <div class="list-group-item">@Html.DropDownListFor(x => x.Condominio, Model.ListaCondominios, "", new { id = "ListaCondominios", @class = "form-control seleciona-form" })</div>
                    </div>
                </div>
            </div>
            <div class="form-row pt-3">
                <div class="col-md-3">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.Telefone, new { @class = "text-uppercase legenda" })</div>
                        <div class="list-group-item">@Html.TextBoxFor(x => x.Telefone, new { @class = "form-control"})</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.Cpf, new { @class = "text-uppercase legenda" })</div>
                        <div class="list-group-item">@Html.TextBoxFor(x => x.Cpf, new { @class = "form-control"})</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.Email, new { @class = "text-uppercase legenda" })</div>
                        <div class="list-group-item">@Html.TextBoxFor(x => x.Email, new { @class = "text-lowercase form-control"})</div>
                    </div>
                </div>
            </div>
            <div class="form-row pt-3">
                <div class="col-md-3">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.DataCadastro, new { @class = "text-uppercase legenda" })</div>
                        <div class="list-group-item">@Html.TextBoxFor(x => x.DataCadastro, new { @class = "form-control"})</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="list-group">
                        <div class="list-group-item">@Html.LabelFor(x => x.RfId, new { @class = "text-uppercase legenda" })</div>
                        <div class="list-group-item">@Html.TextBoxFor(x => x.RfId, new { @class = "form-control"})</div>
                    </div>
                    @Html.ValidationMessageFor(x => x.RfId)
                </div>
            </div>
        </div>
    </form>
</div>

Server/ControlePassageiros.WebApplication/Views/Home/Index.cshtml
@model List<ControlePassageiros.WebApplication.PassageiroResponse>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    .btn-situacao {
        width: 100px !important;
        height: 20px !important;
        font-size: 14px !important;
        padding: 1px !important;
        margin: 0px !important;
    }

    .btn-liberado {
        color: #fff;
        background-color: #28a745;
        border-color: #28a745;
    }

    .bg-liberado {
        width: 100px;
        border: none;
        background-color: #28a745;
        color: white;
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
    }

    .bg-bloqueado {
        width: 100px;
        border: none;
        background-color: #dc3545;
        color: white;
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
    }


    .botao-bloqueado {
        background-color: #f44336 !important;
        width: 30px !important;
        height: 30px !important;
        padding: 5px;
    }

    .botao-editar {
        background-color: #4487bd !important;
        width: 30px !important;
        height: 30px !important;
        padding: 5px;
    }

    .legenda {
        font-weight: 900 !important;
        color: #555 !important;
        font-size: 14px !important;
    }

    .dados {
        font-size: 13px !important;
    }

    .card-box {
        box-shadow: 0 1px 4px 0 rgb(0 0 0 / 48%) !important;
    }

    .card .card-header-success .card-icon, .card .card-header-success .card-text, .card .card-header-success:not(.card-header-icon):not(.card-header-text), .card.bg-success, .card.card-rotate.bg-success .back, .card.card-rotate.bg-success .front {
        background: linear-gradient(60deg,#28a745,#28a745);
    }

    .card-stats .card-header.card-header-icon i {
        font-size: 30px;
        line-height: 40px;
        width: 40px;
        height: 40px;
        text-align: center;
    }

    .fundo-cinza {
        background-color: #eeeeee42 !important;
    }

    .card {
        background-color: white !important;
    }

    .card-legend {
        color: #555 !important;
    }

</style>

<div id="divFiltro">
    @Html.PartialAsync("Listagem", Model).Result
</div>

@Html.PartialAsync("Modal").Result

<script type="text/javascript">
    var $acao = 'cadastrar';

    $(document).ready(function () {
        $('#_modal').on('shown.bs.modal', function () {
            framework.configurarSelect2();

            framework.configurarDatePicker($('#DataCadastro'));

        });

        $('#_modal').on('hidden.bs.modal', function () {
            $acao = 'cadastrar';
        });
    });

    function resetar(_status) {
        const options = {
            url: '@Url.Action("ResetarBase", "Passageiros")',
            type: 'POST',
            dados: { status: _status }
        }

        framework.requisicao(options, function (response) {
            if (response.success) {
                $.notifySuccess(response.message);
                refreshGrid();
                return;
            }

            $.notifyWarning(response.message);
        });
    }

    function cadastrar() {
        $acao = 'cadastrar';

        const arrayBotoes = ['btnLimparModal', 'btnSalvarModal'];
        framework.abrirModalSmall('@Url.Action("Cadastrar", "Home")', 'Cadastro de Usuários', arrayBotoes);
    }

    function salvar() {
        $('#Situacao').val($('#chkSituacao')[0].checked);

        const form = $(document.getElementById("frmCadastro"));
        const url = $acao == 'cadastrar' ? '@Url.Action("Incluir", "Home")' : '@Url.Action("Alterar", "Home")';

        framework.submeterForm(form, url, function (response) {
            if (response.success) {
                $.notifySuccess(response.message);
                framework.fecharModal();

                refreshGrid();
                return;
            }

            $.notifyWarning(response.message);
        });
    }

    function editar(_rfid) {
        $acao = 'editar';

        const arrayBotoes = ['btnSalvarModal'];
        const options = {
            url: '@Url.Action("Editar", "Home")',
            type: 'GET',
            dados: { rfid: _rfid }
        };

        framework.requisicao(options, function (response) {
            framework.carregarModalSmall(response, 'Cadastro de Usuários', arrayBotoes);
        });
    }

    function refreshGrid() {
        $acao = 'cadastrar';

        const options = {
            url: '@Url.Action("Pesquisar", "Home")',
            type: 'GET'
        }

        framework.requisicao(options, function (response) {
            $('#divFiltro').html(response);
        });
    }

    function bloquear(_rfid) {
        const options = {
            url: '@Url.Action("Bloquear", "Passageiros")',
            type: 'GET',
            dados: { rfid: _rfid }
        }

        framework.requisicao(options, function (response) {
            if (response.success) {

                $.notifySuccess(response.message);
                refreshGrid();
                return;
            }

            $.notifyWarning(response.message);
        });
    }

</script>

Server/ControlePassageiros.WebApplication/Views/Home/Listagem.cshtml
@model List<ControlePassageiros.WebApplication.PassageiroResponse>
@{
    Layout = null;
}

<div class="form-row d-flex justify-content-center">
    <div class="col-lg-4 col-md-3 col-sm-12">
        <div class="card card-stats" style="width: 95%;">
            <div class="card-header card-header-info card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">group</i>
                </div>
                <p id="local1" class="card-category font-weight-bold" style="font-size: 25px;"></p>
                <p class="card-category font-weight-bold card-legend" style="font-size: 18px;">Usuários</p>

            </div>
            <div class="card-footer">
                <h3 id="quantidade1" class="card-title font-weight-bold card-legend" style="margin-left: auto; color: #ababab;">Total: @Model.Count</h3>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-3 col-sm-12">
        <div class="card card-stats" style="width: 95%;">
            <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">how_to_reg</i>
                </div>
                <p id="local3" class="card-category font-weight-bold" style="font-size: 25px;"></p>
                <p class="card-category font-weight-bold card-legend" style="font-size: 18px;">Liberados</p>
            </div>
            <div class="card-footer">
                <h3 id="quantidade3" class="card-title font-weight-bold card-legend" style="margin-left: auto; color: #ababab;">Total: @Model.Where(x => x.Situacao).Count()</h3>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-3 col-sm-12">
        <div class="card card-stats" style="width: 95%;">
            <div class="card-header card-header-danger card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">group_off</i>
                </div>
                <p id="local3" class="card-category font-weight-bold" style="font-size: 25px;"></p>
                <p class="card-category font-weight-bold card-legend" style="font-size: 18px;">Bloqueados</p>
            </div>
            <div class="card-footer">
                <h3 id="quantidade3" class="card-title font-weight-bold card-legend" style="margin-left: auto; color: #ababab;">Total: @Model.Where(x => !x.Situacao).Count()</h3>
            </div>
        </div>
    </div>
</div>

<div class="card" style="margin-top: -20px;">
    <div class="card-body fundo-cinza pt-5">

        @foreach (var passageiro in Model)
        {
            <div class="card card-form card-box pt-1">
                <div class="form-row-rel">
                    <div class="col-md-1">
                        <img src="data:image/jpeg;base64,@passageiro.Foto" style="width: 85px; border-radius: 50%;" />
                    </div>

                    <div class="col-md-2 col-sm-12 mt-4 ml-1">
                        <div class="list-group">
                            <div class="list-group-item">@Html.LabelFor(x => x.FirstOrDefault().Nome, new { @class = "text-uppercase legenda" })</div>
                            <div class="list-group-item">@Html.Label("", passageiro.Nome, new { @class = "dados text-uppercase" })</div>
                        </div>
                    </div>

                    <div class="col-md-2 col-sm-12 mt-4">
                        <div class="list-group">
                            <div class="list-group-item">@Html.LabelFor(x => x.FirstOrDefault().Condominio, new { @class = "text-uppercase legenda" })</div>
                            <div class="list-group-item">@Html.Label("", passageiro.Condominio, new { @class = "dados text-uppercase" })</div>
                        </div>
                    </div>

                    <div class="col-md-2 col-sm-12 mt-4">
                        <div class="list-group">
                            <div class="list-group-item">@Html.LabelFor(x => x.FirstOrDefault().Rfid, new { @class = "text-uppercase legenda" })</div>
                            <div class="list-group-item">@Html.Label("", passageiro.Rfid, new { @class = "dados text-uppercase" })</div>
                        </div>
                    </div>

                    <div class="col-md-2 col-sm-12 mt-4">
                        <div class="list-group">
                            <div class="list-group-item">@Html.LabelFor(x => x.FirstOrDefault().StatusAtual, new { @class = "text-uppercase legenda" })</div>

                            @if (passageiro.Situacao)
                            {
                                <button type="button" class="bg-liberado" disabled>@passageiro.StatusAtual</button>
                            }
                            else
                            {
                                <button type="button" class="bg bg-bloqueado">@passageiro.StatusAtual</button>
                            }
                        </div>
                    </div>

                    <div class="col-md-2 col-sm-12 mt-5">
                        <button type="button" rel="tooltip" class="btn botao-editar" data-original-title="" title=""
                            onclick="editar('@passageiro.Rfid');">
                            <i class="material-icons md-20">edit_square</i>
                        </button>

                        <button type="button" rel="tooltip" class="btn botao-bloqueado" data-original-title="" title=""
                            onclick="bloquear('@passageiro.Rfid');">
                            <i class="material-icons md-20">block</i>
                        </button>
                    </div>
                </div>
            </div>
            <br />
        }

        <div class="form-row pull-right">
            @Html.DisplayForModel("BotoesFiltro")
        </div>

    </div>
</div>